# Model configuration
num_layers: 2
hidden_dim: 32
num_heads: 8
head_dim: 32
rope_dim: 32
kv_compression_dim: 16
query_compression_dim: 16 
num_experts: 32
activated_experts: 16
vocab_size : 50258
min_seq_len: 5
max_seq_len: 64 
stride: 8

